/** Reference geography used for seeding. Airport coordinates are approximate and used for distance-based estimates only. */

export const countries = [
  { code: "ID", name: "Indonesia", currency: "IDR", region: "Southeast Asia" },
  { code: "TH", name: "Thailand", currency: "THB", region: "Southeast Asia" },
  { code: "MY", name: "Malaysia", currency: "MYR", region: "Southeast Asia" },
  { code: "JP", name: "Japan", currency: "JPY", region: "East Asia" },
  { code: "SG", name: "Singapore", currency: "SGD", region: "Southeast Asia" },
  { code: "VN", name: "Vietnam", currency: "VND", region: "Southeast Asia" },
  { code: "HK", name: "Hong Kong SAR", currency: "HKD", region: "East Asia" },
  { code: "KR", name: "South Korea", currency: "KRW", region: "East Asia" },
  { code: "AE", name: "United Arab Emirates", currency: "AED", region: "Middle East" },
  { code: "NZ", name: "New Zealand", currency: "NZD", region: "Oceania" },
  { code: "AU", name: "Australia", currency: "AUD", region: "Oceania" },
  { code: "FJ", name: "Fiji", currency: "FJD", region: "Oceania" },
  { code: "KH", name: "Cambodia", currency: "KHR", region: "Southeast Asia" },
  { code: "GB", name: "United Kingdom", currency: "GBP", region: "Europe" },
  { code: "US", name: "United States", currency: "USD", region: "North America" },
] as const;

export const cities = [
  { slug: "denpasar", name: "Bali (Denpasar)", country: "ID", lat: -8.65, lng: 115.22 },
  { slug: "bangkok", name: "Bangkok", country: "TH", lat: 13.75, lng: 100.5 },
  { slug: "kuala-lumpur", name: "Kuala Lumpur", country: "MY", lat: 3.14, lng: 101.69 },
  { slug: "tokyo", name: "Tokyo", country: "JP", lat: 35.68, lng: 139.69 },
  { slug: "singapore", name: "Singapore", country: "SG", lat: 1.35, lng: 103.82 },
  { slug: "phuket", name: "Phuket", country: "TH", lat: 7.88, lng: 98.39 },
  { slug: "da-nang", name: "Da Nang", country: "VN", lat: 16.05, lng: 108.2 },
  { slug: "langkawi", name: "Langkawi", country: "MY", lat: 6.35, lng: 99.8 },
  { slug: "hong-kong", name: "Hong Kong", country: "HK", lat: 22.32, lng: 114.17 },
  { slug: "seoul", name: "Seoul", country: "KR", lat: 37.57, lng: 126.98 },
  { slug: "dubai", name: "Dubai", country: "AE", lat: 25.2, lng: 55.27 },
  { slug: "auckland", name: "Auckland", country: "NZ", lat: -36.85, lng: 174.76 },
  { slug: "melbourne", name: "Melbourne", country: "AU", lat: -37.81, lng: 144.96 },
  { slug: "brisbane", name: "Brisbane", country: "AU", lat: -27.47, lng: 153.03 },
  { slug: "gold-coast", name: "Gold Coast", country: "AU", lat: -28.02, lng: 153.4 },
  { slug: "cairns", name: "Cairns", country: "AU", lat: -16.92, lng: 145.77 },
  { slug: "queenstown", name: "Queenstown", country: "NZ", lat: -45.03, lng: 168.66 },
  { slug: "nadi", name: "Nadi", country: "FJ", lat: -17.8, lng: 177.42 },
  { slug: "phnom-penh", name: "Phnom Penh", country: "KH", lat: 11.56, lng: 104.92 },
  { slug: "ho-chi-minh-city", name: "Ho Chi Minh City", country: "VN", lat: 10.82, lng: 106.63 },
  { slug: "sydney", name: "Sydney", country: "AU", lat: -33.87, lng: 151.21 },
  { slug: "perth", name: "Perth", country: "AU", lat: -31.95, lng: 115.86 },
  { slug: "adelaide", name: "Adelaide", country: "AU", lat: -34.93, lng: 138.6 },
  { slug: "london", name: "London", country: "GB", lat: 51.51, lng: -0.13 },
  { slug: "new-york", name: "New York", country: "US", lat: 40.71, lng: -74.0 },
  { slug: "los-angeles", name: "Los Angeles", country: "US", lat: 34.05, lng: -118.24 },
] as const;

export const airports = [
  { iata: "DPS", name: "Ngurah Rai International", city: "denpasar", lat: -8.748, lng: 115.167 },
  { iata: "BKK", name: "Suvarnabhumi", city: "bangkok", lat: 13.69, lng: 100.75 },
  { iata: "KUL", name: "Kuala Lumpur International", city: "kuala-lumpur", lat: 2.745, lng: 101.71 },
  { iata: "HND", name: "Tokyo Haneda", city: "tokyo", lat: 35.549, lng: 139.78 },
  { iata: "SIN", name: "Changi", city: "singapore", lat: 1.359, lng: 103.989 },
  { iata: "HKT", name: "Phuket International", city: "phuket", lat: 8.11, lng: 98.317 },
  { iata: "DAD", name: "Da Nang International", city: "da-nang", lat: 16.044, lng: 108.199 },
  { iata: "LGK", name: "Langkawi International", city: "langkawi", lat: 6.33, lng: 99.729 },
  { iata: "HKG", name: "Hong Kong International", city: "hong-kong", lat: 22.308, lng: 113.918 },
  { iata: "ICN", name: "Incheon International", city: "seoul", lat: 37.469, lng: 126.451 },
  { iata: "DXB", name: "Dubai International", city: "dubai", lat: 25.253, lng: 55.365 },
  { iata: "AKL", name: "Auckland Airport", city: "auckland", lat: -37.008, lng: 174.792 },
  { iata: "MEL", name: "Melbourne Airport", city: "melbourne", lat: -37.673, lng: 144.843 },
  { iata: "BNE", name: "Brisbane Airport", city: "brisbane", lat: -27.384, lng: 153.117 },
  { iata: "OOL", name: "Gold Coast Airport", city: "gold-coast", lat: -28.164, lng: 153.505 },
  { iata: "CNS", name: "Cairns Airport", city: "cairns", lat: -16.886, lng: 145.755 },
  { iata: "ZQN", name: "Queenstown Airport", city: "queenstown", lat: -45.021, lng: 168.739 },
  { iata: "NAN", name: "Nadi International", city: "nadi", lat: -17.755, lng: 177.443 },
  { iata: "PNH", name: "Phnom Penh International", city: "phnom-penh", lat: 11.547, lng: 104.844 },
  { iata: "SGN", name: "Tan Son Nhat", city: "ho-chi-minh-city", lat: 10.819, lng: 106.652 },
  { iata: "SYD", name: "Sydney Kingsford Smith", city: "sydney", lat: -33.946, lng: 151.177 },
  { iata: "PER", name: "Perth Airport", city: "perth", lat: -31.94, lng: 115.967 },
  { iata: "ADL", name: "Adelaide Airport", city: "adelaide", lat: -34.945, lng: 138.531 },
  { iata: "LHR", name: "London Heathrow", city: "london", lat: 51.47, lng: -0.454 },
  { iata: "JFK", name: "New York JFK", city: "new-york", lat: 40.64, lng: -73.779 },
  { iata: "LAX", name: "Los Angeles International", city: "los-angeles", lat: 33.942, lng: -118.408 },
] as const;
