import { scoreMap, type InterestKey } from "@/lib/travel/interests";
import type { ActivityCategory, DestinationActivity, Faq } from "@/lib/travel/types";

/**
 * Curated destination content. All costs are ESTIMATES in USD (typical mid-season levels),
 * not live provider prices. Hero images are generated placeholders — replace with licensed photography.
 * Interest score order: beach, food, nature, adventure, family, luxury, culture, nightlife, shopping, relaxation.
 */

type Act = [title: string, cat: "a" | "t" | "r", costUsd: number, minutes: number, interests: string];

const CAT: Record<"a" | "t" | "r", ActivityCategory> = { a: "activity", t: "attraction", r: "restaurant" };

function acts(list: Act[]): DestinationActivity[] {
  return list.map(([title, cat, costUsd, durationMin, interests]) => ({
    title,
    category: CAT[cat],
    costUsd,
    durationMin,
    interests: interests.split(",").filter(Boolean) as InterestKey[],
  }));
}

export type DestinationSeed = {
  slug: string;
  name: string;
  countryCode: string;
  citySlug: string;
  airportCode: string;
  theme: "beach" | "city" | "mountain" | "desert";
  tagline: string;
  overview: string;
  bestMonths: number[];
  avoidMonths: number[];
  interestScores: Record<InterestKey, number>;
  familyScore: number;
  days: [number, number];
  hotel: [number, number, number]; // budget, mid, luxury per room per night
  daily: [number, number, number]; // food, transport, activities per person per day
  activities: DestinationActivity[];
  transportTips: string;
  foodHighlights: string;
  travelTips: string[];
  faq: Faq[];
  related: string[];
};

export const destinations: DestinationSeed[] = [
  {
    slug: "bali",
    name: "Bali",
    countryCode: "ID",
    citySlug: "denpasar",
    airportCode: "DPS",
    theme: "beach",
    tagline: "Rice terraces, surf breaks and temple sunsets on Indonesia's island of the gods.",
    overview:
      "Bali balances beach clubs and surf towns with jungle retreats and centuries-old temples. Ubud is the cultural and wellness heart, the Bukit Peninsula has the cliff-top beaches, and Canggu and Seminyak cover cafés and nightlife. Good value at every budget level.",
    bestMonths: [4, 5, 6, 7, 8, 9, 10],
    avoidMonths: [1, 2],
    interestScores: scoreMap([5, 4, 4, 4, 4, 5, 4, 4, 3, 5]),
    familyScore: 4,
    days: [6, 10],
    hotel: [45, 95, 320],
    daily: [25, 15, 30],
    activities: acts([
      ["Sunrise trek and hot-spring soak at Mount Batur", "a", 45, 360, "adventure,nature"],
      ["Tegallalang and Jatiluwih rice terrace walk", "t", 8, 180, "nature,culture"],
      ["Uluwatu cliff temple and Kecak fire dance", "t", 12, 180, "culture"],
      ["Surf lesson at Canggu or Kuta", "a", 35, 150, "beach,adventure"],
      ["Nusa Penida day trip: Kelingking and Crystal Bay", "a", 60, 600, "nature,adventure,beach"],
      ["Warung food crawl: babi guling, nasi campur, satay", "r", 15, 120, "food"],
      ["Ubud cooking class with market visit", "r", 35, 240, "food,culture"],
      ["Beach-club afternoon and sunset drinks in Seminyak", "a", 30, 240, "nightlife,luxury,relaxation,beach"],
      ["Balinese spa and massage", "a", 25, 120, "relaxation,luxury"],
      ["Sacred Monkey Forest and Ubud Palace", "t", 10, 150, "culture,family"],
    ]),
    transportTips:
      "Taxis are cheap but traffic is heavy. Most visitors hire a private driver by the day (typically US$35–50) or use ride-hailing apps; scooters are common but require a valid licence and insurance.",
    foodHighlights: "Warungs serve full meals for a few dollars; beach-club and fine dining prices are closer to Western levels.",
    travelTips: [
      "Split your stay between two areas (e.g. Ubud + coast) instead of moving every night.",
      "Dress modestly and carry a sarong for temple visits.",
      "Drink bottled or filtered water only.",
    ],
    faq: [
      { q: "How many days do I need in Bali?", a: "Seven to ten days lets you combine Ubud, a beach area and one day trip without rushing." },
      { q: "Is Bali good for families?", a: "Yes. Many resorts have kids' clubs, and beaches like Sanur have calm water. Watch for uneven pavements and heavy traffic with prams." },
      { q: "Do I need a visa for Bali?", a: "Most nationalities need a visa on arrival or e-visa. Requirements change, so check the official Indonesian immigration site before you travel." },
    ],
    related: ["phuket", "da-nang", "langkawi"],
  },
  {
    slug: "bangkok",
    name: "Bangkok",
    countryCode: "TH",
    citySlug: "bangkok",
    airportCode: "BKK",
    theme: "city",
    tagline: "Street food, gilded temples, rooftop bars and some of Asia's best shopping.",
    overview:
      "Bangkok is loud, humid and endlessly rewarding. Royal palaces and river temples sit beside mega-malls, night markets and world-class street food. It is also an easy hub for beach add-ons in the Gulf of Thailand or Andaman coast.",
    bestMonths: [11, 12, 1, 2],
    avoidMonths: [4, 5, 9, 10],
    interestScores: scoreMap([1, 5, 1, 2, 3, 4, 5, 5, 5, 2]),
    familyScore: 3,
    days: [3, 6],
    hotel: [40, 85, 260],
    daily: [22, 8, 25],
    activities: acts([
      ["Grand Palace and Wat Phra Kaew", "t", 16, 180, "culture"],
      ["Wat Pho and Wat Arun by river ferry", "t", 10, 210, "culture"],
      ["Chinatown (Yaowarat) street-food night", "r", 18, 150, "food,nightlife"],
      ["Chatuchak Weekend Market", "a", 20, 240, "shopping"],
      ["Rooftop cocktails above the skyline", "a", 30, 120, "nightlife,luxury"],
      ["Thai cooking class", "r", 35, 240, "food,culture"],
      ["Damnoen Saduak or Amphawa floating market day trip", "a", 40, 420, "culture,family"],
      ["Traditional Thai massage", "a", 12, 90, "relaxation"],
      ["Muay Thai fight night", "a", 45, 180, "adventure,nightlife"],
    ]),
    transportTips: "The BTS Skytrain and MRT are fast and cheap. Use river boats for the old town and ride-hailing for short hops.",
    foodHighlights: "A satisfying street-food meal is a few dollars; Michelin-listed street stalls and modern Thai restaurants are also affordable by global standards.",
    travelTips: [
      "Temples require covered shoulders and knees.",
      "Start sightseeing early — midday heat is intense.",
      "Agree on taxi meters or use a ride-hailing app.",
    ],
    faq: [
      { q: "How long should I spend in Bangkok?", a: "Three to four days covers the highlights; add more if you want day trips or a food-focused trip." },
      { q: "Is Bangkok safe for tourists?", a: "It is generally safe. Watch for common tourist scams such as unsolicited tuk-tuk 'tours' and gem shops." },
    ],
    related: ["phuket", "kuala-lumpur", "ho-chi-minh-city"],
  },
  {
    slug: "kuala-lumpur",
    name: "Kuala Lumpur",
    countryCode: "MY",
    citySlug: "kuala-lumpur",
    airportCode: "KUL",
    theme: "city",
    tagline: "Malay, Chinese and Indian food cultures under the Petronas Towers.",
    overview:
      "Kuala Lumpur pairs modern towers and huge shopping centres with heritage streets and outstanding, inexpensive food. Batu Caves, rainforest in the city and easy flights to Langkawi or Penang make it a flexible short trip.",
    bestMonths: [5, 6, 7, 8],
    avoidMonths: [10, 11],
    interestScores: scoreMap([0, 5, 2, 1, 3, 3, 4, 4, 5, 1]),
    familyScore: 4,
    days: [3, 5],
    hotel: [35, 75, 220],
    daily: [20, 8, 20],
    activities: acts([
      ["Petronas Twin Towers observation deck", "t", 25, 90, "culture,family"],
      ["Batu Caves and Hindu temple complex", "t", 5, 150, "culture"],
      ["Jalan Alor night-food street", "r", 15, 120, "food,nightlife"],
      ["Bukit Bintang and Pavilion shopping", "a", 40, 240, "shopping"],
      ["Petaling Street and Central Market heritage walk", "t", 5, 180, "culture,shopping"],
      ["Aquaria KLCC or KL Bird Park", "t", 22, 150, "family,nature"],
      ["Local breakfast trail: nasi lemak, roti canai, teh tarik", "r", 8, 90, "food"],
      ["Sky-bar evening", "a", 30, 120, "nightlife,luxury"],
    ]),
    transportTips: "LRT/MRT/monorail cover the centre. Ride-hailing is cheap and reliable. KLIA Ekspres links the airport to KL Sentral.",
    foodHighlights: "Hawker centres and mamak stalls make eating very cheap; upscale rooftop and hotel dining still costs less than in most capitals.",
    travelTips: [
      "Book Petronas Towers slots ahead — they sell out.",
      "Carry a light rain jacket; afternoon showers are common.",
    ],
    faq: [
      { q: "Is Kuala Lumpur worth a long stay?", a: "It suits 3–5 days, ideally combined with Langkawi, Penang or the Cameron Highlands." },
    ],
    related: ["singapore", "langkawi", "bangkok"],
  },
  {
    slug: "tokyo",
    name: "Tokyo",
    countryCode: "JP",
    citySlug: "tokyo",
    airportCode: "HND",
    theme: "city",
    tagline: "Neon districts, quiet shrines and the world's most obsessive food scene.",
    overview:
      "Tokyo rewards curiosity. Ultra-efficient trains link Shibuya's crossings, Asakusa's temples, Akihabara's arcades and Shimokitazawa's vintage shops. Day trips reach Mount Fuji, Nikko and Kamakura. Spring blossoms and autumn colours are the peak seasons.",
    bestMonths: [3, 4, 5, 10, 11],
    avoidMonths: [7, 8],
    interestScores: scoreMap([0, 5, 3, 2, 4, 3, 5, 4, 5, 2]),
    familyScore: 4,
    days: [5, 8],
    hotel: [75, 150, 450],
    daily: [45, 15, 35],
    activities: acts([
      ["Senso-ji Temple and Asakusa", "t", 0, 150, "culture"],
      ["Shibuya Crossing and Shibuya Sky", "t", 20, 120, "culture,nightlife"],
      ["Tsukiji Outer Market food tour", "r", 40, 180, "food"],
      ["Day trip to Hakone or Mount Fuji area", "a", 90, 600, "nature,adventure"],
      ["teamLab digital art museum", "t", 30, 150, "culture,family"],
      ["Akihabara arcades and anime shops", "a", 30, 180, "shopping,family"],
      ["Golden Gai bar-hopping in Shinjuku", "a", 45, 180, "nightlife"],
      ["Ramen and izakaya evening", "r", 25, 120, "food,nightlife"],
      ["Meiji Shrine and Harajuku", "t", 5, 180, "culture,shopping"],
      ["Onsen or sento soak", "a", 20, 90, "relaxation"],
    ]),
    transportTips: "Buy a Suica or Pasmo IC card (mobile versions are available). Trains stop around midnight, so plan late-night returns.",
    foodHighlights: "Excellent food at every price: convenience-store breakfasts, US$8 ramen and set lunches, through to high-end sushi.",
    travelTips: [
      "Carry some cash — many small restaurants are cash-only.",
      "Tipping is not customary.",
      "Book popular attractions such as teamLab in advance.",
    ],
    faq: [
      { q: "When is the best time to visit Tokyo?", a: "Late March–April for cherry blossom and October–November for autumn colour. Summer is hot and humid." },
      { q: "Is Tokyo expensive?", a: "Accommodation can be pricey, but food and transport offer strong value. Budget travellers can do it comfortably with capsule hotels and set-meal lunches." },
    ],
    related: ["seoul", "hong-kong", "singapore"],
  },
  {
    slug: "singapore",
    name: "Singapore",
    countryCode: "SG",
    citySlug: "singapore",
    airportCode: "SIN",
    theme: "city",
    tagline: "A spotless, safe city-state with hawker-centre food and family-friendly attractions.",
    overview:
      "Singapore is compact, easy to navigate and extremely family-friendly. Gardens by the Bay, Sentosa, the zoo family and hawker centres deliver a lot in a few days. Hotels are the main cost; food and transport can be very affordable.",
    bestMonths: [2, 3, 4, 5, 6, 7],
    avoidMonths: [11, 12],
    interestScores: scoreMap([1, 5, 3, 2, 5, 4, 3, 4, 5, 2]),
    familyScore: 5,
    days: [3, 5],
    hotel: [110, 190, 480],
    daily: [40, 10, 35],
    activities: acts([
      ["Gardens by the Bay and Cloud Forest", "t", 28, 180, "nature,family"],
      ["Hawker centre feast: chicken rice, laksa, satay", "r", 12, 90, "food"],
      ["Singapore Zoo or Night Safari", "t", 45, 240, "family,nature"],
      ["Sentosa beaches and Universal Studios", "a", 75, 480, "family,beach,adventure"],
      ["Orchard Road shopping", "a", 40, 180, "shopping"],
      ["Little India and Chinatown heritage walk", "t", 5, 180, "culture,food"],
      ["Marina Bay light show and rooftop drinks", "a", 35, 150, "nightlife,luxury"],
    ]),
    transportTips: "The MRT is excellent and contactless payment works on trains and buses. Taxis are more expensive than in neighbouring countries.",
    foodHighlights: "Hawker centres give Michelin-recognised dishes for a few dollars; restaurants and bars are costly.",
    travelTips: ["Book Sentosa and zoo tickets online to save time.", "It's hot and humid year-round; carry water."],
    faq: [
      { q: "Is Singapore good for a short stopover?", a: "Yes — two to three days covers the highlights, and Changi's transit tools make it easy to add a stopover." },
    ],
    related: ["kuala-lumpur", "bangkok", "hong-kong"],
  },
  {
    slug: "phuket",
    name: "Phuket",
    countryCode: "TH",
    citySlug: "phuket",
    airportCode: "HKT",
    theme: "beach",
    tagline: "Andaman Sea beaches, island-hopping boat days and lively Patong nights.",
    overview:
      "Thailand's largest island offers everything from quiet southern coves to party-focused Patong. Boat trips reach Phi Phi, James Bond Island and the Similan Islands (seasonal). Great for beach holidays with easy add-ons.",
    bestMonths: [11, 12, 1, 2, 3, 4],
    avoidMonths: [9, 10],
    interestScores: scoreMap([5, 4, 3, 4, 4, 5, 2, 5, 3, 4]),
    familyScore: 4,
    days: [5, 9],
    hotel: [45, 100, 350],
    daily: [28, 15, 40],
    activities: acts([
      ["Phi Phi Islands speedboat day tour", "a", 65, 540, "beach,nature,adventure"],
      ["Phang Nga Bay and James Bond Island", "a", 60, 480, "nature,adventure"],
      ["Old Phuket Town walking and café stop", "t", 10, 180, "culture,food"],
      ["Big Buddha and Wat Chalong", "t", 5, 150, "culture"],
      ["Bangla Road nightlife in Patong", "a", 40, 180, "nightlife"],
      ["Thai massage on the beach", "a", 15, 90, "relaxation,beach"],
      ["Sunset seafood dinner at Rawai or Kata", "r", 30, 120, "food,relaxation"],
      ["Snorkelling or diving session", "a", 55, 240, "beach,adventure"],
    ]),
    transportTips: "There's no metro; use ride-hailing apps or hire a scooter/car. Songthaew buses are cheap but slow. Airport transfers are best pre-booked.",
    foodHighlights: "Fresh seafood and southern Thai curries. Beachfront restaurants cost more than local eateries in Phuket Town.",
    travelTips: ["Check the sea conditions in May–October — some beaches have red-flag rip currents.", "Agree on boat-tour pick-up points in advance."],
    faq: [
      { q: "Which beach area is best in Phuket?", a: "Kata and Karon suit families, Patong suits nightlife, and Kamala or Surin are quieter and more upmarket." },
    ],
    related: ["bali", "bangkok", "langkawi"],
  },
  {
    slug: "da-nang",
    name: "Da Nang",
    countryCode: "VN",
    citySlug: "da-nang",
    airportCode: "DAD",
    theme: "beach",
    tagline: "Long sandy beaches, Marble Mountains and the gateway to Hoi An.",
    overview:
      "Da Nang is Vietnam's easygoing coastal city with a long beach, bridges lit at night and great seafood. It is 45 minutes from historic Hoi An and near the Ba Na Hills and Hai Van Pass.",
    bestMonths: [3, 4, 5, 6, 7, 8],
    avoidMonths: [10, 11],
    interestScores: scoreMap([5, 4, 4, 3, 4, 3, 3, 2, 2, 4]),
    familyScore: 4,
    days: [4, 7],
    hotel: [30, 65, 200],
    daily: [18, 8, 20],
    activities: acts([
      ["My Khe Beach morning swim", "a", 0, 120, "beach,relaxation"],
      ["Hoi An Ancient Town and lantern-lit river", "t", 12, 300, "culture,food"],
      ["Ba Na Hills and Golden Bridge", "t", 40, 360, "family,nature"],
      ["Marble Mountains climb", "t", 6, 150, "adventure,culture"],
      ["Hai Van Pass scooter or car trip", "a", 45, 300, "adventure,nature"],
      ["Mi Quang noodles and seafood on the beach", "r", 10, 90, "food"],
      ["Han River Dragon Bridge weekend show", "t", 0, 60, "family,nightlife"],
    ]),
    transportTips: "Grab and taxis are cheap; day tours to Hoi An by taxi cost around US$20 each way.",
    foodHighlights: "Very affordable local food: mi quang, banh xeo and fresh seafood. Beach restaurants cost more.",
    travelTips: ["Typhoon season is Sept–Nov.", "Buy Ba Na Hills tickets online to skip lines."],
    faq: [{ q: "How far is Hoi An from Da Nang?", a: "About 30 km — roughly 45 minutes by taxi." }],
    related: ["ho-chi-minh-city", "bangkok", "bali"],
  },
  {
    slug: "langkawi",
    name: "Langkawi",
    countryCode: "MY",
    citySlug: "langkawi",
    airportCode: "LGK",
    theme: "beach",
    tagline: "Duty-free island, mangrove tours and quiet beaches in the Andaman Sea.",
    overview:
      "Langkawi is a relaxed archipelago known for beaches, mangrove kayaking, the SkyBridge and duty-free shopping. It suits couples and families wanting an easy, lower-key beach break.",
    bestMonths: [12, 1, 2, 3],
    avoidMonths: [9, 10],
    interestScores: scoreMap([5, 3, 5, 3, 4, 4, 1, 1, 3, 5]),
    familyScore: 4,
    days: [4, 7],
    hotel: [40, 90, 300],
    daily: [22, 15, 30],
    activities: acts([
      ["Langkawi SkyCab and SkyBridge", "t", 25, 180, "nature,family"],
      ["Mangrove river tour and eagle feeding", "a", 30, 180, "nature,family,adventure"],
      ["Island-hopping to Pulau Dayang Bunting", "a", 35, 300, "beach,nature"],
      ["Pantai Cenang beach afternoon", "a", 0, 240, "beach,relaxation"],
      ["Duty-free shopping in Kuah", "a", 30, 180, "shopping"],
      ["Sunset seafood dinner in Cenang", "r", 20, 120, "food,relaxation"],
    ]),
    transportTips: "Taxis are fixed-price and can be costly; renting a car or scooter gives the most flexibility.",
    foodHighlights: "Malay and seafood restaurants are affordable. Alcohol is duty-free and cheap by regional standards.",
    travelTips: ["Rent a car for 1–2 days rather than for the whole stay.", "Cable-car closes in strong wind or rain."],
    faq: [{ q: "Is Langkawi good for a short trip?", a: "Yes — four nights is enough to enjoy beaches, a mangrove tour and the SkyBridge." }],
    related: ["phuket", "kuala-lumpur", "bali"],
  },
  {
    slug: "hong-kong",
    name: "Hong Kong",
    countryCode: "HK",
    citySlug: "hong-kong",
    airportCode: "HKG",
    theme: "city",
    tagline: "Skyline views, dim sum, hiking trails and the Star Ferry, all in one compact city.",
    overview:
      "Hong Kong stacks a huge amount into a small area: harbour skyline, tea houses, hiking trails and beaches, outlying islands and world-class dim sum. Autumn brings the best weather.",
    bestMonths: [10, 11, 12, 3, 4],
    avoidMonths: [7, 8, 9],
    interestScores: scoreMap([0, 5, 3, 2, 4, 4, 4, 4, 5, 1]),
    familyScore: 4,
    days: [3, 5],
    hotel: [90, 160, 420],
    daily: [40, 10, 30],
    activities: acts([
      ["Victoria Peak tram and skyline views", "t", 15, 150, "nature,family"],
      ["Dim sum breakfast in Sheung Wan or Mong Kok", "r", 15, 90, "food"],
      ["Star Ferry across Victoria Harbour", "t", 1, 60, "culture,family"],
      ["Tian Tan Buddha and Ngong Ping 360", "t", 30, 300, "culture,nature"],
      ["Temple Street Night Market", "a", 15, 120, "shopping,nightlife,food"],
      ["Lantau or Dragon's Back hike", "a", 5, 240, "nature,adventure"],
      ["Lan Kwai Fong bar hop", "a", 45, 180, "nightlife"],
    ]),
    transportTips: "Get an Octopus card. The MTR is fast, and double-decker trams and ferries are scenic and cheap.",
    foodHighlights: "From US$3 noodle stalls to Michelin-star dim sum. Dining in central districts costs more than in Kowloon.",
    travelTips: ["Avoid typhoon season (Jul–Sep) if you can.", "Check entry requirements for your passport."],
    faq: [{ q: "How many days in Hong Kong?", a: "Three full days covers the highlights; add a day for Lantau or a Macau side trip." }],
    related: ["tokyo", "seoul", "singapore"],
  },
  {
    slug: "seoul",
    name: "Seoul",
    countryCode: "KR",
    citySlug: "seoul",
    airportCode: "ICN",
    theme: "city",
    tagline: "Palaces, K-beauty, barbecue and all-night neighbourhoods.",
    overview:
      "Seoul mixes royal palaces and hanok villages with cutting-edge fashion, cafés, K-pop culture and late-night dining. Spring and autumn are ideal; winters are cold but clear.",
    bestMonths: [4, 5, 9, 10],
    avoidMonths: [7, 8],
    interestScores: scoreMap([0, 5, 3, 2, 3, 3, 5, 5, 5, 2]),
    familyScore: 3,
    days: [4, 7],
    hotel: [60, 115, 330],
    daily: [35, 10, 25],
    activities: acts([
      ["Gyeongbokgung Palace and Bukchon Hanok Village", "t", 4, 240, "culture"],
      ["Korean BBQ dinner", "r", 30, 120, "food,nightlife"],
      ["Myeongdong and Hongdae shopping", "a", 40, 240, "shopping"],
      ["N Seoul Tower at sunset", "t", 15, 120, "nature,culture"],
      ["Gwangjang Market street food", "r", 12, 90, "food"],
      ["DMZ half-day tour", "a", 65, 480, "culture,adventure"],
      ["Jjimjilbang (Korean spa) evening", "a", 15, 180, "relaxation"],
    ]),
    transportTips: "Subway and bus network is extensive; T-money card works on both. AREX links Incheon Airport to the city.",
    foodHighlights: "Great value: BBQ, stews and street food. Cafés and dessert spots are part of the culture.",
    travelTips: ["Download Naver Map or KakaoMap; Google Maps is limited.", "Book DMZ tours well in advance."],
    faq: [{ q: "Is Seoul good in winter?", a: "Yes if you enjoy snow, hot food and heated floors, but pack for sub-zero temperatures." }],
    related: ["tokyo", "hong-kong", "singapore"],
  },
  {
    slug: "dubai",
    name: "Dubai",
    countryCode: "AE",
    citySlug: "dubai",
    airportCode: "DXB",
    theme: "desert",
    tagline: "Record-breaking towers, desert safaris and beach-resort luxury.",
    overview:
      "Dubai is a year-round stopover and winter-sun destination with futuristic architecture, malls, desert experiences, and resort beaches. Winter (Nov–Mar) has the best weather; summer heat is extreme.",
    bestMonths: [11, 12, 1, 2, 3],
    avoidMonths: [6, 7, 8],
    interestScores: scoreMap([3, 4, 2, 3, 4, 5, 3, 4, 5, 4]),
    familyScore: 4,
    days: [3, 6],
    hotel: [80, 170, 500],
    daily: [50, 20, 60],
    activities: acts([
      ["Burj Khalifa observation deck", "t", 45, 120, "culture,luxury"],
      ["Desert safari with dune bashing and BBQ", "a", 60, 360, "adventure,family"],
      ["Old Dubai: souks, abra ferry, Al Fahidi", "t", 5, 210, "culture,shopping"],
      ["Dubai Mall and fountain show", "a", 0, 210, "shopping,family"],
      ["Jumeirah beach day", "a", 15, 240, "beach,relaxation"],
      ["Brunch at a beachfront hotel", "r", 70, 180, "food,luxury"],
      ["Aquaventure or Wild Wadi waterpark", "t", 85, 300, "family,adventure"],
    ]),
    transportTips: "The Metro is efficient along the main corridor; taxis and ride-hailing fill the gaps. Summer heat makes walking difficult.",
    foodHighlights: "Anything from budget shawarma to celebrity-chef restaurants. Alcohol is only served in licensed venues.",
    travelTips: ["Respect local dress and behaviour guidelines.", "Book major attractions online to avoid queues."],
    faq: [{ q: "Is Dubai expensive?", a: "Luxury is a highlight, but the Metro, food courts and free attractions keep costs reasonable. Hotel rates vary widely with season." }],
    related: ["singapore", "hong-kong", "kuala-lumpur"],
  },
  {
    slug: "auckland",
    name: "Auckland",
    countryCode: "NZ",
    citySlug: "auckland",
    airportCode: "AKL",
    theme: "city",
    tagline: "Harbour city with volcanic cones, island wine trails and easy nature.",
    overview:
      "Auckland is New Zealand's largest city, with harbours on both sides, volcanic viewpoints, Waiheke Island wineries and quick access to beaches and rainforest. It also serves as the entry point to the North Island.",
    bestMonths: [12, 1, 2, 3],
    avoidMonths: [6, 7],
    interestScores: scoreMap([3, 4, 5, 4, 4, 3, 3, 3, 3, 3]),
    familyScore: 4,
    days: [3, 6],
    hotel: [90, 160, 380],
    daily: [50, 18, 45],
    activities: acts([
      ["Waiheke Island wine tasting", "a", 90, 480, "food,luxury,relaxation"],
      ["Sky Tower and viewing deck", "t", 35, 90, "culture,family"],
      ["Mount Eden and One Tree Hill walk", "t", 0, 120, "nature"],
      ["Piha Beach and Waitakere Ranges", "a", 10, 300, "nature,beach,adventure"],
      ["Viaduct Harbour dinner", "r", 45, 120, "food,nightlife"],
      ["Rangitoto Island volcano hike", "a", 45, 360, "nature,adventure"],
    ]),
    transportTips: "Public transport is workable for the CBD; hire a car for west-coast beaches and day trips.",
    foodHighlights: "Strong café culture and seafood. Dining costs are similar to Australian cities.",
    travelTips: ["Weather changes fast; layer up.", "Ferries to Waiheke and Devonport are scenic and simple."],
    faq: [{ q: "Is Auckland good for a stopover?", a: "Yes for 3–4 days; if you can spare more, add Rotorua or the Bay of Islands." }],
    related: ["queenstown", "melbourne", "fiji"],
  },
  {
    slug: "melbourne",
    name: "Melbourne",
    countryCode: "AU",
    citySlug: "melbourne",
    airportCode: "MEL",
    theme: "city",
    tagline: "Coffee laneways, street art, live music and the Great Ocean Road on the doorstep.",
    overview:
      "Melbourne is a food and culture capital, with hidden laneways, sport, festivals and quick access to the Great Ocean Road, Yarra Valley wineries and Phillip Island.",
    bestMonths: [3, 4, 11, 12],
    avoidMonths: [6, 7],
    interestScores: scoreMap([1, 5, 2, 1, 3, 3, 5, 4, 5, 2]),
    familyScore: 4,
    days: [3, 6],
    hotel: [100, 170, 380],
    daily: [55, 15, 35],
    activities: acts([
      ["Laneway coffee and street-art walk", "t", 15, 180, "culture,food"],
      ["Great Ocean Road day tour", "a", 140, 720, "nature,adventure"],
      ["Queen Victoria Market and food hall", "r", 20, 150, "food,shopping"],
      ["Yarra Valley wine and cheese day", "a", 110, 480, "food,luxury,relaxation"],
      ["Phillip Island penguin parade", "a", 35, 360, "family,nature"],
      ["Live music in Fitzroy or Collingwood", "a", 25, 180, "nightlife,culture"],
    ]),
    transportTips: "Trams in the CBD are free; a myki card covers trains and other trams.",
    foodHighlights: "Excellent Vietnamese, Italian, Greek and brunch culture; expect mid-to-high prices.",
    travelTips: ["Weather can shift four seasons in a day.", "Book Great Ocean Road tours early in summer."],
    faq: [{ q: "How many days do I need for the Great Ocean Road?", a: "A long day trip works, but an overnight in Apollo Bay or Port Campbell is more relaxed." }],
    related: ["brisbane", "auckland", "gold-coast"],
  },
  {
    slug: "brisbane",
    name: "Brisbane",
    countryCode: "AU",
    citySlug: "brisbane",
    airportCode: "BNE",
    theme: "city",
    tagline: "River city with a subtropical climate, koalas and easy access to islands.",
    overview:
      "Brisbane is sunny, laid-back and family-friendly, with South Bank's lagoon, koala sanctuaries and day trips to Moreton Island and the Sunshine Coast hinterland.",
    bestMonths: [4, 5, 9, 10],
    avoidMonths: [1, 2],
    interestScores: scoreMap([2, 4, 3, 2, 5, 3, 2, 3, 3, 3]),
    familyScore: 5,
    days: [3, 5],
    hotel: [95, 160, 350],
    daily: [50, 15, 35],
    activities: acts([
      ["South Bank Parklands and Streets Beach", "t", 0, 180, "family,relaxation"],
      ["Lone Pine Koala Sanctuary", "t", 45, 180, "family,nature"],
      ["Moreton Island day trip", "a", 130, 600, "adventure,nature,beach"],
      ["Mount Coot-tha lookout", "t", 0, 120, "nature"],
      ["Riverside dinner and CityCat ride", "r", 45, 150, "food,relaxation"],
    ]),
    transportTips: "Use go card on buses, trains and the CityCat ferry. Car hire helps with day trips.",
    foodHighlights: "Fresh produce, coffee and Queensland seafood; prices similar to other major Australian cities.",
    travelTips: ["Summer is hot and humid with storms.", "Combine with the Gold Coast or Sunshine Coast."],
    faq: [{ q: "Is Brisbane good for families?", a: "Yes. Free water lagoons, wildlife parks and mild winters make it easy with kids." }],
    related: ["gold-coast", "cairns", "melbourne"],
  },
  {
    slug: "gold-coast",
    name: "Gold Coast",
    countryCode: "AU",
    citySlug: "gold-coast",
    airportCode: "OOL",
    theme: "beach",
    tagline: "Surf beaches, theme parks and hinterland rainforest in one Queensland stretch.",
    overview:
      "The Gold Coast is famous for its 50+ km of beaches, theme parks and surf culture. Hinterland rainforest at Springbrook and Lamington offers a quieter side.",
    bestMonths: [4, 5, 9, 10],
    avoidMonths: [1, 2],
    interestScores: scoreMap([5, 3, 3, 4, 5, 3, 1, 4, 3, 3]),
    familyScore: 5,
    days: [4, 7],
    hotel: [110, 180, 400],
    daily: [50, 20, 55],
    activities: acts([
      ["Surf lesson at Burleigh or Currumbin", "a", 55, 120, "beach,adventure"],
      ["Theme park day (Movie World, Sea World or Dreamworld)", "t", 100, 480, "family,adventure"],
      ["Springbrook or Lamington rainforest walk", "a", 10, 300, "nature"],
      ["Burleigh Heads markets and brunch", "r", 25, 150, "food,relaxation"],
      ["Surfers Paradise nightlife", "a", 40, 180, "nightlife"],
      ["Currumbin Wildlife Sanctuary", "t", 55, 210, "family,nature"],
    ]),
    transportTips: "The G:link tram runs along the coast; ride-hailing and hire cars cover the hinterland.",
    foodHighlights: "Beachside cafés and modern Australian restaurants; casual meals are moderate, resort dining is pricier.",
    travelTips: ["Swim only between the red and yellow flags.", "Theme-park bundles save money."],
    faq: [{ q: "How many days on the Gold Coast?", a: "Four to five days is enough for beaches, one theme park and a hinterland day." }],
    related: ["brisbane", "cairns", "melbourne"],
  },
  {
    slug: "cairns",
    name: "Cairns",
    countryCode: "AU",
    citySlug: "cairns",
    airportCode: "CNS",
    theme: "beach",
    tagline: "Gateway to the Great Barrier Reef and Daintree Rainforest.",
    overview:
      "Cairns is the base for reef snorkelling and diving, Daintree rainforest tours, Kuranda scenic rail and Atherton Tablelands waterfalls. The dry season (Jun–Oct) has clear skies and calm seas.",
    bestMonths: [6, 7, 8, 9, 10],
    avoidMonths: [1, 2, 3],
    interestScores: scoreMap([4, 3, 5, 5, 4, 3, 2, 2, 1, 4]),
    familyScore: 4,
    days: [4, 7],
    hotel: [90, 150, 320],
    daily: [50, 25, 70],
    activities: acts([
      ["Great Barrier Reef snorkel or dive day trip", "a", 190, 600, "adventure,nature,beach"],
      ["Daintree Rainforest and Cape Tribulation tour", "a", 150, 600, "nature,adventure"],
      ["Kuranda Scenic Railway and Skyrail", "t", 130, 480, "nature,family"],
      ["Cairns Esplanade Lagoon and night markets", "a", 10, 180, "family,relaxation,shopping"],
      ["Waterfall circuit on the Atherton Tablelands", "a", 40, 420, "nature"],
      ["Fresh seafood dinner on the Esplanade", "r", 45, 120, "food"],
    ]),
    transportTips: "Most tours include hotel pickups. Rent a car for waterfall and Port Douglas days.",
    foodHighlights: "Reef fish, barramundi and tropical fruit. Menus are moderate to high by international standards.",
    travelTips: ["Stinger-suit season runs roughly Nov–May.", "Book reef trips early in school holidays."],
    faq: [{ q: "When is the best time for the Great Barrier Reef?", a: "June to October offers the driest weather and best visibility; stinger season is from November to May." }],
    related: ["gold-coast", "brisbane", "fiji"],
  },
  {
    slug: "queenstown",
    name: "Queenstown",
    countryCode: "NZ",
    citySlug: "queenstown",
    airportCode: "ZQN",
    theme: "mountain",
    tagline: "Adventure capital ringed by alpine peaks, lakes and vineyards.",
    overview:
      "Queenstown offers bungy jumping, jet-boating, skiing and hiking on Lake Wakatipu. Milford Sound, Arrowtown and Central Otago wine country are day-trip options.",
    bestMonths: [12, 1, 2, 3, 7, 8],
    avoidMonths: [5],
    interestScores: scoreMap([0, 3, 5, 5, 3, 4, 1, 3, 1, 3]),
    familyScore: 3,
    days: [4, 7],
    hotel: [120, 210, 500],
    daily: [55, 20, 90],
    activities: acts([
      ["Bungy jump at Kawarau Bridge", "a", 150, 120, "adventure"],
      ["Milford Sound day cruise", "a", 190, 720, "nature"],
      ["Skyline Gondola and luge", "t", 65, 150, "family,adventure"],
      ["Shotover Jet boat ride", "a", 100, 60, "adventure,family"],
      ["Arrowtown historic village and wine tasting", "a", 40, 300, "culture,food"],
      ["Lakeside burger and dinner in town", "r", 25, 90, "food"],
    ]),
    transportTips: "The town centre is walkable. A car is helpful for Arrowtown, Glenorchy and Cardrona ski fields.",
    foodHighlights: "Strong brunch and dinner options; costs are high because of tourism demand.",
    travelTips: ["Book activities before you arrive in peak season.", "Snow chains may be required in winter."],
    faq: [{ q: "Is Queenstown good for a winter trip?", a: "Yes — July and August offer skiing at Coronet Peak and The Remarkables, but book lodging early." }],
    related: ["auckland", "melbourne", "fiji"],
  },
  {
    slug: "fiji",
    name: "Fiji",
    countryCode: "FJ",
    citySlug: "nadi",
    airportCode: "NAN",
    theme: "beach",
    tagline: "Coral lagoons, resort islands and legendary Fijian hospitality.",
    overview:
      "Fiji's Mamanuca and Yasawa islands offer clear water, snorkelling and easy resort stays, many with kids' clubs. Nadi is the main gateway, and resort transfers are typically by boat or small aircraft.",
    bestMonths: [5, 6, 7, 8, 9, 10],
    avoidMonths: [1, 2, 3],
    interestScores: scoreMap([5, 2, 4, 4, 5, 5, 2, 1, 1, 5]),
    familyScore: 5,
    days: [5, 9],
    hotel: [70, 140, 450],
    daily: [35, 15, 45],
    activities: acts([
      ["Mamanuca island day cruise", "a", 110, 480, "beach,nature,family"],
      ["Snorkelling on the coral reef", "a", 45, 180, "beach,nature,adventure"],
      ["Kava ceremony and village visit", "t", 25, 150, "culture"],
      ["Sabeto Mud Pool and Hot Springs", "a", 30, 180, "relaxation,family"],
      ["Sunset lovo feast", "r", 40, 150, "food,culture"],
      ["Sigatoka River safari", "a", 90, 420, "adventure,culture"],
    ]),
    transportTips: "Resort transfers are usually pre-booked. Inter-island ferries operate on set schedules.",
    foodHighlights: "Island resorts price food in-house, so all-inclusive packages can help you manage costs.",
    travelTips: ["Bring reef-safe sunscreen.", "Check cyclone season (Nov–Apr) travel insurance cover."],
    faq: [{ q: "Is Fiji good for families?", a: "Yes. Many Fijian resorts specialise in family stays with kids' clubs and shallow lagoons." }],
    related: ["bali", "queenstown", "cairns"],
  },
  {
    slug: "phnom-penh",
    name: "Phnom Penh",
    countryCode: "KH",
    citySlug: "phnom-penh",
    airportCode: "PNH",
    theme: "city",
    tagline: "Riverside capital of Cambodia — history, markets and inexpensive dining.",
    overview:
      "Phnom Penh is a compact riverside city with the Royal Palace, Silver Pagoda, Russian Market and moving historical sites. It pairs naturally with Siem Reap and coastal Kampot. Prices are low across the board.",
    bestMonths: [11, 12, 1, 2],
    avoidMonths: [7, 8, 9, 10],
    interestScores: scoreMap([0, 3, 1, 2, 2, 1, 5, 3, 3, 1]),
    familyScore: 2,
    days: [2, 4],
    hotel: [25, 55, 160],
    daily: [15, 6, 20],
    activities: acts([
      ["Royal Palace and Silver Pagoda", "t", 10, 150, "culture"],
      ["Tuol Sleng Genocide Museum and Choeung Ek", "t", 15, 240, "culture"],
      ["Russian Market and Central Market", "a", 15, 180, "shopping"],
      ["Riverside sunset cruise", "a", 15, 90, "relaxation"],
      ["Khmer amok and street-food evening", "r", 10, 120, "food"],
    ]),
    transportTips: "Tuk-tuks and Grab are cheap and easy. Carry small US-dollar notes; USD is widely accepted.",
    foodHighlights: "Very affordable Khmer food; international and rooftop dining is still low-cost.",
    travelTips: ["Dress respectfully at memorial sites.", "Pre-arrange visas online where possible."],
    faq: [{ q: "How many days in Phnom Penh?", a: "Two to three days is enough; most travellers continue to Siem Reap for Angkor Wat." }],
    related: ["ho-chi-minh-city", "bangkok", "da-nang"],
  },
  {
    slug: "ho-chi-minh-city",
    name: "Ho Chi Minh City",
    countryCode: "VN",
    citySlug: "ho-chi-minh-city",
    airportCode: "SGN",
    theme: "city",
    tagline: "Motorbike-buzzing southern hub with coffee culture, history and superb street food.",
    overview:
      "Ho Chi Minh City (Saigon) blends French colonial buildings, war-history museums, rooftop bars and one of Southeast Asia's best street-food scenes. The Cu Chi Tunnels and Mekong Delta are easy day trips.",
    bestMonths: [12, 1, 2, 3, 4],
    avoidMonths: [6, 7, 8, 9, 10],
    interestScores: scoreMap([0, 5, 2, 2, 3, 2, 4, 4, 4, 1]),
    familyScore: 3,
    days: [3, 6],
    hotel: [28, 60, 190],
    daily: [16, 6, 18],
    activities: acts([
      ["War Remnants Museum and Reunification Palace", "t", 5, 210, "culture"],
      ["Ben Thanh Market and street-food tour", "r", 25, 180, "food,shopping"],
      ["Cu Chi Tunnels half-day trip", "a", 25, 300, "culture,adventure"],
      ["Mekong Delta day tour", "a", 40, 600, "nature,culture,family"],
      ["Bui Vien and rooftop bars", "a", 30, 180, "nightlife"],
      ["Vietnamese coffee crawl", "r", 8, 120, "food,culture"],
    ]),
    transportTips: "Grab bikes and cars are cheap and reliable. Crossing streets is an art — walk steadily.",
    foodHighlights: "Pho, banh mi, bun thit nuong and much more for just a few dollars.",
    travelTips: ["Keep phones secure on motorbike-heavy streets.", "Arrange an e-visa in advance if required."],
    faq: [{ q: "How many days in Ho Chi Minh City?", a: "Three to four days including a day trip to the Cu Chi Tunnels or Mekong Delta." }],
    related: ["da-nang", "phnom-penh", "bangkok"],
  },
];
